[package]
name = "payment-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
polars = "0.51.0"
rust_decimal = "1.38.0"
thiserror = "2.0.16"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
